name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Виконується при пуші в main (або можна замінити на свою гілку)
#  pull_request:
#    branches:
#      - master  # Або на pull request у main

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest  # Використовуємо контейнер з Ubuntu
    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v4  # Завантажує код репозиторію

      - name: Встановлення Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # --- Backend ---
      - name: Встановлення залежностей для backend
        run: |
          cd backend
          npm install

      - name: Запуск тестів для backend
        run: |
          cd backend
          npm test

      # --- Frontend ---
      - name: Встановлення залежностей для frontend
        run: |
          cd frontend
          npm install

      - name: Білд frontend
        run: |
          cd frontend
          npm run build

      #      --- Docker Hub ---

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
